# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/search"
  to = "https://api.themoviedb.org/3/search/movie/"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"