[[redirects]]
  from = "/search"
  to = "https://api.themoviedb.org/3/search/movie/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"